//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUGEN_SYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int BookingID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public Nullable<int> PassengerID { get; set; }
        public Nullable<int> FareID { get; set; }
        public Nullable<decimal> TotalFarePaid { get; set; }
        public string SeatNumber { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> AgentID { get; set; }
    
        public virtual Fare Fare { get; set; }
        public virtual Passengers Passengers { get; set; }
        public virtual Schedule Schedule { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
