//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUGEN_SYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fare()
        {
            this.Bookings = new HashSet<Bookings>();
        }
    
        public int FareID { get; set; }
        public Nullable<int> DepartureStationID { get; set; }
        public Nullable<int> ArrivalStationID { get; set; }
        public Nullable<decimal> FareAmount { get; set; }
        public string ClassOfService { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual Stations Stations { get; set; }
        public virtual Stations Stations1 { get; set; }
    }
}
