//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MUGEN_SYSTEM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MugenSystemDBEntities : DbContext
    {
        public MugenSystemDBEntities()
            : base("name=MugenSystemDBEntities") 
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bookings> Bookings { get; set; }
        public virtual DbSet<Fare> Fare { get; set; }
        public virtual DbSet<Passengers> Passengers { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Stations> Stations { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trains> Trains { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
    }
}
